version: "3.8"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PASSWORD: 12345
      AppName: no
      ENCRYPT: chacha20-ietf-poly1305
      PORT: 80
    ports:
      - "8080:8080"
      - "81:80"
      - "443:443"